import type { ResourceDefinition } from '@/types'

export const azureVMSizes = {
  generalPurpose: [
    { value: 'Standard_B1s', label: 'B1s (1 vCPU, 1 GiB)' },
    { value: 'Standard_B1ms', label: 'B1ms (1 vCPU, 2 GiB)' },
    { value: 'Standard_B2s', label: 'B2s (2 vCPU, 4 GiB)' },
    { value: 'Standard_B2ms', label: 'B2ms (2 vCPU, 8 GiB)' },
    { value: 'Standard_B4ms', label: 'B4ms (4 vCPU, 16 GiB)' },
    { value: 'Standard_B8ms', label: 'B8ms (8 vCPU, 32 GiB)' },
    { value: 'Standard_B12ms', label: 'B12ms (12 vCPU, 48 GiB)' },
    { value: 'Standard_B16ms', label: 'B16ms (16 vCPU, 64 GiB)' },
    { value: 'Standard_B20ms', label: 'B20ms (20 vCPU, 80 GiB)' },
    { value: 'Standard_D2s_v3', label: 'D2s_v3 (2 vCPU, 8 GiB)' },
    { value: 'Standard_D4s_v3', label: 'D4s_v3 (4 vCPU, 16 GiB)' },
    { value: 'Standard_D8s_v3', label: 'D8s_v3 (8 vCPU, 32 GiB)' },
    { value: 'Standard_D16s_v3', label: 'D16s_v3 (16 vCPU, 64 GiB)' },
    { value: 'Standard_D32s_v3', label: 'D32s_v3 (32 vCPU, 128 GiB)' },
    { value: 'Standard_D48s_v3', label: 'D48s_v3 (48 vCPU, 192 GiB)' },
    { value: 'Standard_D64s_v3', label: 'D64s_v3 (64 vCPU, 256 GiB)' },
    { value: 'Standard_D2ds_v4', label: 'D2ds_v4 (2 vCPU, 8 GiB)' },
    { value: 'Standard_D4ds_v4', label: 'D4ds_v4 (4 vCPU, 16 GiB)' },
    { value: 'Standard_D8ds_v4', label: 'D8ds_v4 (8 vCPU, 32 GiB)' },
    { value: 'Standard_D16ds_v4', label: 'D16ds_v4 (16 vCPU, 64 GiB)' },
    { value: 'Standard_D32ds_v4', label: 'D32ds_v4 (32 vCPU, 128 GiB)' },
    { value: 'Standard_D48ds_v4', label: 'D48ds_v4 (48 vCPU, 192 GiB)' },
    { value: 'Standard_D64ds_v4', label: 'D64ds_v4 (64 vCPU, 256 GiB)' },
    { value: 'Standard_D2s_v4', label: 'D2s_v4 (2 vCPU, 8 GiB)' },
    { value: 'Standard_D4s_v4', label: 'D4s_v4 (4 vCPU, 16 GiB)' },
    { value: 'Standard_D8s_v4', label: 'D8s_v4 (8 vCPU, 32 GiB)' },
    { value: 'Standard_D16s_v4', label: 'D16s_v4 (16 vCPU, 64 GiB)' },
    { value: 'Standard_D32s_v4', label: 'D32s_v4 (32 vCPU, 128 GiB)' },
    { value: 'Standard_DC1s_v2', label: 'DC1s_v2 (1 vCPU, 4 GiB)' },
    { value: 'Standard_DC2s_v2', label: 'DC2s_v2 (2 vCPU, 8 GiB)' },
    { value: 'Standard_DC4s_v2', label: 'DC4s_v2 (4 vCPU, 16 GiB)' },
    { value: 'Standard_DC8s_v2', label: 'DC8s_v2 (8 vCPU, 32 GiB)' },
    { value: 'Standard_DC16s_v3', label: 'DC16s_v3 (16 vCPU, 64 GiB)' },
    { value: 'Standard_DC24s_v3', label: 'DC24s_v3 (24 vCPU, 96 GiB)' },
    { value: 'Standard_DC32s_v3', label: 'DC32s_v3 (32 vCPU, 128 GiB)' },
    { value: 'Standard_DC48s_v3', label: 'DC48s_v3 (48 vCPU, 192 GiB)' },
    { value: 'Standard_DC96s_v3', label: 'DC96s_v3 (96 vCPU, 384 GiB)' },
  ],
  computeOptimized: [
    { value: 'Standard_F1', label: 'F1 (1 vCPU, 2 GiB)' },
    { value: 'Standard_F2', label: 'F2 (2 vCPU, 4 GiB)' },
    { value: 'Standard_F4', label: 'F4 (4 vCPU, 8 GiB)' },
    { value: 'Standard_F8', label: 'F8 (8 vCPU, 16 GiB)' },
    { value: 'Standard_F16', label: 'F16 (16 vCPU, 32 GiB)' },
    { value: 'Standard_F2s', label: 'F2s (2 vCPU, 4 GiB)' },
    { value: 'Standard_F4s', label: 'F4s (4 vCPU, 8 GiB)' },
    { value: 'Standard_F8s', label: 'F8s (8 vCPU, 16 GiB)' },
    { value: 'Standard_F16s', label: 'F16s (16 vCPU, 32 GiB)' },
    { value: 'Standard_F2s_v2', label: 'F2s_v2 (2 vCPU, 4 GiB)' },
    { value: 'Standard_F4s_v2', label: 'F4s_v2 (4 vCPU, 8 GiB)' },
    { value: 'Standard_F8s_v2', label: 'F8s_v2 (8 vCPU, 16 GiB)' },
    { value: 'Standard_F16s_v2', label: 'F16s_v2 (16 vCPU, 32 GiB)' },
    { value: 'Standard_F32s_v2', label: 'F32s_v2 (32 vCPU, 64 GiB)' },
    { value: 'Standard_F48s_v2', label: 'F48s_v2 (48 vCPU, 96 GiB)' },
    { value: 'Standard_F64s_v2', label: 'F64s_v2 (64 vCPU, 128 GiB)' },
    { value: 'Standard_F72s_v2', label: 'F72s_v2 (72 vCPU, 144 GiB)' },
    { value: 'Standard_F2ds_v5', label: 'F2ds_v5 (2 vCPU, 4 GiB)' },
    { value: 'Standard_F4ds_v5', label: 'F4ds_v5 (4 vCPU, 8 GiB)' },
    { value: 'Standard_F8ds_v5', label: 'F8ds_v5 (8 vCPU, 16 GiB)' },
    { value: 'Standard_F16ds_v5', label: 'F16ds_v5 (16 vCPU, 32 GiB)' },
    { value: 'Standard_F32ds_v5', label: 'F32ds_v5 (32 vCPU, 64 GiB)' },
    { value: 'Standard_F48ds_v5', label: 'F48ds_v5 (48 vCPU, 96 GiB)' },
    { value: 'Standard_F64ds_v5', label: 'F64ds_v5 (64 vCPU, 128 GiB)' },
    { value: 'Standard_FX4mds', label: 'FX4mds (4 vCPU, 32 GiB)' },
    { value: 'Standard_FX12mds', label: 'FX12mds (12 vCPU, 96 GiB)' },
    { value: 'Standard_FX24mds', label: 'FX24mds (24 vCPU, 192 GiB)' },
    { value: 'Standard_FX48mds', label: 'FX48mds (48 vCPU, 384 GiB)' },
  ],
  memoryOptimized: [
    { value: 'Standard_E2s_v3', label: 'E2s_v3 (2 vCPU, 16 GiB)' },
    { value: 'Standard_E4s_v3', label: 'E4s_v3 (4 vCPU, 32 GiB)' },
    { value: 'Standard_E8s_v3', label: 'E8s_v3 (8 vCPU, 64 GiB)' },
    { value: 'Standard_E16s_v3', label: 'E16s_v3 (16 vCPU, 128 GiB)' },
    { value: 'Standard_E20s_v3', label: 'E20s_v3 (20 vCPU, 160 GiB)' },
    { value: 'Standard_E32s_v3', label: 'E32s_v3 (32 vCPU, 256 GiB)' },
    { value: 'Standard_E48s_v3', label: 'E48s_v3 (48 vCPU, 384 GiB)' },
    { value: 'Standard_E64s_v3', label: 'E64s_v3 (64 vCPU, 432 GiB)' },
    { value: 'Standard_E2s_v4', label: 'E2s_v4 (2 vCPU, 16 GiB)' },
    { value: 'Standard_E4s_v4', label: 'E4s_v4 (4 vCPU, 32 GiB)' },
    { value: 'Standard_E8s_v4', label: 'E8s_v4 (8 vCPU, 64 GiB)' },
    { value: 'Standard_E16s_v4', label: 'E16s_v4 (16 vCPU, 128 GiB)' },
    { value: 'Standard_E32s_v4', label: 'E32s_v4 (32 vCPU, 256 GiB)' },
    { value: 'Standard_E48s_v4', label: 'E48s_v4 (48 vCPU, 384 GiB)' },
    { value: 'Standard_E64s_v4', label: 'E64s_v4 (64 vCPU, 512 GiB)' },
    { value: 'Standard_E2ds_v4', label: 'E2ds_v4 (2 vCPU, 16 GiB)' },
    { value: 'Standard_E4ds_v4', label: 'E4ds_v4 (4 vCPU, 32 GiB)' },
    { value: 'Standard_E8ds_v4', label: 'E8ds_v4 (8 vCPU, 64 GiB)' },
    { value: 'Standard_E16ds_v4', label: 'E16ds_v4 (16 vCPU, 128 GiB)' },
    { value: 'Standard_E20ds_v4', label: 'E20ds_v4 (20 vCPU, 160 GiB)' },
    { value: 'Standard_E32ds_v4', label: 'E32ds_v4 (32 vCPU, 256 GiB)' },
    { value: 'Standard_E48ds_v4', label: 'E48ds_v4 (48 vCPU, 384 GiB)' },
    { value: 'Standard_E64ds_v4', label: 'E64ds_v4 (64 vCPU, 512 GiB)' },
    { value: 'Standard_E2ds_v5', label: 'E2ds_v5 (2 vCPU, 16 GiB)' },
    { value: 'Standard_E4ds_v5', label: 'E4ds_v5 (4 vCPU, 32 GiB)' },
    { value: 'Standard_E8ds_v5', label: 'E8ds_v5 (8 vCPU, 64 GiB)' },
    { value: 'Standard_E16ds_v5', label: 'E16ds_v5 (16 vCPU, 128 GiB)' },
    { value: 'Standard_E20ds_v5', label: 'E20ds_v5 (20 vCPU, 160 GiB)' },
    { value: 'Standard_E32ds_v5', label: 'E32ds_v5 (32 vCPU, 256 GiB)' },
    { value: 'Standard_E48ds_v5', label: 'E48ds_v5 (48 vCPU, 384 GiB)' },
    { value: 'Standard_E64ds_v5', label: 'E64ds_v5 (64 vCPU, 512 GiB)' },
    { value: 'Standard_E96ds_v5', label: 'E96ds_v5 (96 vCPU, 672 GiB)' },
    { value: 'Standard_E4as_v4', label: 'E4as_v4 (4 vCPU, 32 GiB)' },
    { value: 'Standard_E8as_v4', label: 'E8as_v4 (8 vCPU, 64 GiB)' },
    { value: 'Standard_E16as_v4', label: 'E16as_v4 (16 vCPU, 128 GiB)' },
    { value: 'Standard_E20as_v4', label: 'E20as_v4 (20 vCPU, 160 GiB)' },
    { value: 'Standard_E32as_v4', label: 'E32as_v4 (32 vCPU, 256 GiB)' },
    { value: 'Standard_E48as_v4', label: 'E48as_v4 (48 vCPU, 384 GiB)' },
    { value: 'Standard_E64as_v4', label: 'E64as_v4 (64 vCPU, 512 GiB)' },
    { value: 'Standard_E96as_v4', label: 'E96as_v4 (96 vCPU, 672 GiB)' },
    { value: 'Standard_E4as_v5', label: 'E4as_v5 (4 vCPU, 32 GiB)' },
    { value: 'Standard_E8as_v5', label: 'E8as_v5 (8 vCPU, 64 GiB)' },
    { value: 'Standard_E16as_v5', label: 'E16as_v5 (16 vCPU, 128 GiB)' },
    { value: 'Standard_E20as_v5', label: 'E20as_v5 (20 vCPU, 160 GiB)' },
    { value: 'Standard_E32as_v5', label: 'E32as_v5 (32 vCPU, 256 GiB)' },
    { value: 'Standard_E48as_v5', label: 'E48as_v5 (48 vCPU, 384 GiB)' },
    { value: 'Standard_E64as_v5', label: 'E64as_v5 (64 vCPU, 512 GiB)' },
    { value: 'Standard_E96as_v5', label: 'E96as_v5 (96 vCPU, 672 GiB)' },
    { value: 'Standard_E104id_v5', label: 'E104ids_v5 (104 vCPU, 1.9 TiB)' },
    { value: 'Standard_M8ms', label: 'M8ms (8 vCPU, 208 GiB)' },
    { value: 'Standard_M16ms', label: 'M16ms (16 vCPU, 416 GiB)' },
    { value: 'Standard_M32ms', label: 'M32ms (32 vCPU, 832 GiB)' },
    { value: 'Standard_M64ms', label: 'M64ms (64 vCPU, 1.7 TiB)' },
    { value: 'Standard_M128ms', label: 'M128ms (128 vCPU, 3.8 TiB)' },
    { value: 'Standard_M128s', label: 'M128s (128 vCPU, 3.8 TiB)' },
    { value: 'Standard_M32ls', label: 'M32ls (32 vCPU, 512 GiB)' },
    { value: 'Standard_M64ls', label: 'M64ls (64 vCPU, 1.0 TiB)' },
    { value: 'Standard_M16s_v2', label: 'M16s_v2 (16 vCPU, 286 GiB)' },
    { value: 'Standard_M32s_v2', label: 'M32s_v2 (32 vCPU, 572 GiB)' },
    { value: 'Standard_M64s_v2', label: 'M64s_v2 (64 vCPU, 1.1 TiB)' },
    { value: 'Standard_M96s_v2', label: 'M96s_v2 (96 vCPU, 1.8 TiB)' },
    { value: 'Standard_M128s_v2', label: 'M128s_v2 (128 vCPU, 2.0 TiB)' },
    { value: 'Standard_M192ims_v2', label: 'M192ims_v2 (192 vCPU, 4.0 TiB)' },
    { value: 'Standard_M208ms_v2', label: 'M208ms_v2 (208 vCPU, 5.7 TiB)' },
    { value: 'Standard_M416ms_v2', label: 'M416ms_v2 (416 vCPU, 11.4 TiB)' },
  ],
  storageOptimized: [
    { value: 'Standard_L4s', label: 'L4s (4 vCPU, 32 GiB)' },
    { value: 'Standard_L8s', label: 'L8s (8 vCPU, 64 GiB)' },
    { value: 'Standard_L16s', label: 'L16s (16 vCPU, 128 GiB)' },
    { value: 'Standard_L32s', label: 'L32s (32 vCPU, 256 GiB)' },
    { value: 'Standard_L8s_v2', label: 'L8s_v2 (8 vCPU, 64 GiB)' },
    { value: 'Standard_L16s_v2', label: 'L16s_v2 (16 vCPU, 128 GiB)' },
    { value: 'Standard_L32s_v2', label: 'L32s_v2 (32 vCPU, 256 GiB)' },
    { value: 'Standard_L48s_v2', label: 'L48s_v2 (48 vCPU, 384 GiB)' },
    { value: 'Standard_L64s_v2', label: 'L64s_v2 (64 vCPU, 512 GiB)' },
    { value: 'Standard_L80s_v2', label: 'L80s_v2 (80 vCPU, 640 GiB)' },
    { value: 'Standard_L8as_v3', label: 'L8as_v3 (8 vCPU, 64 GiB)' },
    { value: 'Standard_L16as_v3', label: 'L16as_v3 (16 vCPU, 128 GiB)' },
    { value: 'Standard_L32as_v3', label: 'L32as_v3 (32 vCPU, 256 GiB)' },
    { value: 'Standard_L48as_v3', label: 'L48as_v3 (48 vCPU, 384 GiB)' },
    { value: 'Standard_L64as_v3', label: 'L64as_v3 (64 vCPU, 512 GiB)' },
    { value: 'Standard_L96as_v3', label: 'L96as_v3 (96 vCPU, 768 GiB)' },
  ],
  gpu: [
    { value: 'Standard_NC4as_T4_v3', label: 'NC4as_T4_v3 (4 vCPU, 28 GiB, 1x T4)' },
    { value: 'Standard_NC8as_T4_v3', label: 'NC8as_T4_v3 (8 vCPU, 56 GiB, 1x T4)' },
    { value: 'Standard_NC16as_T4_v3', label: 'NC16as_T4_v3 (16 vCPU, 110 GiB, 1x T4)' },
    { value: 'Standard_NC24as_T4_v3', label: 'NC24as_T4_v3 (24 vCPU, 220 GiB, 2x T4)' },
    { value: 'Standard_NC24ads_A10_v4', label: 'NC24ads_A10_v4 (24 vCPU, 220 GiB, 1x A10)' },
    { value: 'Standard_NC48ads_A100_v4', label: 'NC48ads_A100_v4 (48 vCPU, 440 GiB, 1x A100)' },
    { value: 'Standard_NC96ads_A100_v4', label: 'NC96ads_A100_v4 (96 vCPU, 880 GiB, 2x A100)' },
    { value: 'Standard_NC6s_v2', label: 'NC6s_v2 (6 vCPU, 112 GiB, 1x P40)' },
    { value: 'Standard_NC12s_v2', label: 'NC12s_v2 (12 vCPU, 224 GiB, 2x P40)' },
    { value: 'Standard_NC24s_v2', label: 'NC24s_v2 (24 vCPU, 448 GiB, 4x P40)' },
    { value: 'Standard_NC6s_v3', label: 'NC6s_v3 (6 vCPU, 112 GiB, 1x V100)' },
    { value: 'Standard_NC12s_v3', label: 'NC12s_v3 (12 vCPU, 224 GiB, 2x V100)' },
    { value: 'Standard_NC24s_v3', label: 'NC24s_v3 (24 vCPU, 448 GiB, 4x V100)' },
    { value: 'Standard_NV4as_v4', label: 'NV4as_v4 (8 vCPU, 56 GiB, 1x AMD)' },
    { value: 'Standard_NV8as_v4', label: 'NV8as_v4 (16 vCPU, 112 GiB, 2x AMD)' },
    { value: 'Standard_NV16as_v4', label: 'NV16as_v4 (32 vCPU, 220 GiB, 4x AMD)' },
    { value: 'Standard_NV6', label: 'NV6 (6 vCPU, 56 GiB, 1x M60)' },
    { value: 'Standard_NV12', label: 'NV12 (12 vCPU, 112 GiB, 2x M60)' },
    { value: 'Standard_NV24', label: 'NV24 (24 vCPU, 224 GiB, 4x M60)' },
    { value: 'Standard_ND96isr_h100_v5', label: 'ND96isr_h100_v5 (96 vCPU, 900 GiB, 8x H100)' },
    { value: 'Standard_ND40rs_v2', label: 'ND40rs_v2 (40 vCPU, 672 GiB, 8x V100)' },
    { value: 'Standard_ND96ams_a100_v4', label: 'ND96ams_a100_v4 (96 vCPU, 1.9 TiB, 8x A100)' },
  ],
  highPerformance: [
    { value: 'Standard_H8', label: 'H8 (8 vCPU, 56 GiB)' },
    { value: 'Standard_H16', label: 'H16 (16 vCPU, 112 GiB)' },
    { value: 'Standard_H8m', label: 'H8m (8 vCPU, 112 GiB)' },
    { value: 'Standard_H16m', label: 'H16m (16 vCPU, 224 GiB)' },
    { value: 'Standard_H16mr', label: 'H16mr (16 vCPU, 224 GiB)' },
    { value: 'Standard_HB120rs_v2', label: 'HB120rs_v2 (120 vCPU, 480 GiB)' },
    { value: 'Standard_HB60rs', label: 'HB60rs (60 vCPU, 228 GiB)' },
    { value: 'Standard_HC44rs', label: 'HC44rs (44 vCPU, 352 GiB)' },
    { value: 'Standard_HX176rs', label: 'HX176rs (176 vCPU, 1.8 TiB)' },
    { value: 'Standard_HX276rs', label: 'HX276rs (276 vCPU, 2.8 TiB)' },
    { value: 'Standard_HX277rs_v2', label: 'HX277rs_v2 (277 vCPU, 3.8 TiB)' },
    { value: 'Standard_HX376rs', label: 'HX376rs (376 vCPU, 4.0 TiB)' },
    { value: 'Standard_HB120-16rs_v2', label: 'HB120-16rs_v2 (120 vCPU, 480 GiB)' },
    { value: 'Standard_HB120-32rs_v2', label: 'HB120-32rs_v2 (120 vCPU, 480 GiB)' },
    { value: 'Standard_HB120-64rs_v2', label: 'HB120-64rs_v2 (120 vCPU, 480 GiB)' },
    { value: 'Standard_HB120-96rs_v2', label: 'HB120-96rs_v2 (120 vCPU, 480 GiB)' },
  ],
}

const allAzureVMSizes = [
  ...azureVMSizes.generalPurpose,
  ...azureVMSizes.computeOptimized,
  ...azureVMSizes.memoryOptimized,
  ...azureVMSizes.storageOptimized,
  ...azureVMSizes.gpu,
  ...azureVMSizes.highPerformance,
]

export const azureResources: ResourceDefinition[] = [
  {
    type: 'azurerm_subscription',
    label: 'Azure Subscription',
    category: 'hierarchy',
    icon: 'CreditCard',
    provider: 'azure',
    description: 'Azure Subscription - Root of Azure hierarchy',
    inputs: [
      { name: 'subscription_id', label: 'Subscription ID', type: 'string', required: true },
      { name: 'display_name', label: 'Display Name', type: 'string', required: true },
      { name: 'tenant_id', label: 'Tenant ID', type: 'string', required: false },
    ],
    outputs: ['subscription_id', 'display_name', 'tenant_id'],
  },
  {
    type: 'azurerm_resource_group',
    label: 'Resource Group',
    category: 'hierarchy',
    icon: 'Folder',
    provider: 'azure',
    description: 'Azure Resource Group - Container for resources',
    inputs: [
      { name: 'name', label: 'Resource Group Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'subscription_id', label: 'Subscription ID', type: 'string', required: true },
      { name: 'tags', label: 'Tags', type: 'object', required: false },
    ],
    outputs: ['id', 'name', 'location'],
  },
  {
    type: 'azurerm_virtual_network',
    label: 'Virtual Network',
    category: 'network',
    icon: 'Network',
    provider: 'azure',
    description: 'Azure Virtual Network',
    inputs: [
      { name: 'name', label: 'VNet Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'address_space', label: 'Address Space', type: 'array', required: true, default: ['10.0.0.0/16'] },
      { name: 'dns_servers', label: 'DNS Servers', type: 'array', required: false },
    ],
    outputs: ['id', 'name', 'address_space'],
  },
  {
    type: 'azurerm_subnet',
    label: 'Subnet',
    category: 'network',
    icon: 'Network',
    provider: 'azure',
    description: 'Azure Subnet - Nested under Virtual Network',
    inputs: [
      { name: 'name', label: 'Subnet Name', type: 'string', required: true },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'virtual_network_name', label: 'Virtual Network', type: 'string', required: true },
      { name: 'address_prefixes', label: 'Address Prefixes', type: 'array', required: true },
      { name: 'service_endpoints', label: 'Service Endpoints', type: 'array', required: false },
    ],
    outputs: ['id', 'name', 'address_prefix'],
  },
  {
    type: 'azurerm_linux_virtual_machine',
    label: 'Linux VM',
    category: 'compute',
    icon: 'Server',
    provider: 'azure',
    description: 'Azure Linux Virtual Machine',
    inputs: [
      { name: 'name', label: 'VM Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group_name', label: 'Resource Group Name', type: 'string', required: true },
      { name: 'size', label: 'VM Size', type: 'select', required: true, default: 'Standard_DS1_v2', options: allAzureVMSizes },
      { name: 'network_interface_ids', label: 'Network Interface IDs', type: 'array', required: true },
      { name: 'admin_username', label: 'Admin Username', type: 'string', required: true, default: 'adminuser' },
      { name: 'admin_password', label: 'Admin Password', type: 'string', required: true },
      { name: 'computer_name', label: 'Computer Name', type: 'string', required: false },
      { name: 'custom_data', label: 'Custom Data (Base64)', type: 'string', required: false },
      { name: 'disable_password_authentication', label: 'Disable Password Auth', type: 'boolean', required: false, default: false },
      { name: 'encryption_at_host_enabled', label: 'Encryption at Host', type: 'boolean', required: false, default: false },
      { name: 'patch_mode', label: 'Patch Mode', type: 'select', required: false, default: 'ImageDefault', options: [
        { value: 'ImageDefault', label: 'Image Default' },
        { value: 'AutomaticByPlatform', label: 'Automatic By Platform' },
      ]},
      { name: 'availability_set_id', label: 'Availability Set ID', type: 'string', required: false },
      { name: 'proximity_placement_group_id', label: 'Proximity Placement Group ID', type: 'string', required: false },
      { name: 'zones', label: 'Availability Zones', type: 'array', required: false },
      { name: 'os_disk', label: 'OS Disk (JSON)', type: 'object', required: true, default: { name: 'myOsDisk', caching: 'ReadWrite', storage_account_type: 'Premium_LRS' } },
      { name: 'source_image_reference', label: 'Source Image Reference (JSON)', type: 'object', required: true, default: { publisher: 'Canonical', offer: '0001-com-ubuntu-server-jammy', sku: '22_04-lts', version: 'latest' } },
      { name: 'boot_diagnostics', label: 'Boot Diagnostics (JSON)', type: 'object', required: false },
      { name: 'tags', label: 'Tags', type: 'object', required: false },
    ],
    outputs: ['id', 'name', 'private_ip_address', 'public_ip_address'],
  },
  {
    type: 'azurerm_windows_virtual_machine',
    label: 'Windows VM',
    category: 'compute',
    icon: 'Server',
    provider: 'azure',
    description: 'Azure Windows Virtual Machine',
    inputs: [
      { name: 'name', label: 'VM Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group_name', label: 'Resource Group Name', type: 'string', required: true },
      { name: 'size', label: 'VM Size', type: 'select', required: true, default: 'Standard_DS1_v2', options: allAzureVMSizes },
      { name: 'network_interface_ids', label: 'Network Interface IDs', type: 'array', required: true },
      { name: 'admin_username', label: 'Admin Username', type: 'string', required: true, default: 'azureuser' },
      { name: 'admin_password', label: 'Admin Password', type: 'string', required: true },
      { name: 'computer_name', label: 'Computer Name', type: 'string', required: false },
      { name: 'custom_data', label: 'Custom Data (Base64)', type: 'string', required: false },
      { name: 'encryption_at_host_enabled', label: 'Encryption at Host', type: 'boolean', required: false, default: false },
      { name: 'license_type', label: 'License Type', type: 'select', required: false, default: 'None', options: [
        { value: 'None', label: 'None' },
        { value: 'Windows_Client', label: 'Windows Client' },
        { value: 'Windows_Server', label: 'Windows Server' },
      ]},
      { name: 'automatic_updates_enabled', label: 'Automatic Updates Enabled', type: 'boolean', required: false, default: true },
      { name: 'patch_mode', label: 'Patch Mode', type: 'select', required: false, default: 'AutomaticByOS', options: [
        { value: 'Manual', label: 'Manual' },
        { value: 'AutomaticByOS', label: 'Automatic By OS' },
        { value: 'AutomaticByPlatform', label: 'Automatic By Platform' },
      ]},
      { name: 'availability_set_id', label: 'Availability Set ID', type: 'string', required: false },
      { name: 'proximity_placement_group_id', label: 'Proximity Placement Group ID', type: 'string', required: false },
      { name: 'zones', label: 'Availability Zones', type: 'array', required: false },
      { name: 'os_disk', label: 'OS Disk (JSON)', type: 'object', required: true, default: { name: 'myOsDisk', caching: 'ReadWrite', storage_account_type: 'Premium_LRS' } },
      { name: 'source_image_reference', label: 'Source Image Reference (JSON)', type: 'object', required: true, default: { publisher: 'MicrosoftWindowsServer', offer: 'WindowsServer', sku: '2022-datacenter-azure-edition', version: 'latest' } },
      { name: 'boot_diagnostics', label: 'Boot Diagnostics (JSON)', type: 'object', required: false },
      { name: 'tags', label: 'Tags', type: 'object', required: false },
    ],
    outputs: ['id', 'name', 'private_ip_address', 'public_ip_address', 'admin_password'],
  },
  {
    type: 'azurerm_virtual_machine_extension',
    label: 'VM Extension',
    category: 'compute',
    icon: 'Server',
    provider: 'azure',
    description: 'Azure Virtual Machine Extension for custom scripts',
    inputs: [
      { name: 'name', label: 'Extension Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group_name', label: 'Resource Group Name', type: 'string', required: true },
      { name: 'virtual_machine_id', label: 'Virtual Machine ID', type: 'string', required: true },
      { name: 'publisher', label: 'Publisher', type: 'string', required: true, default: 'Microsoft.Compute' },
      { name: 'type', label: 'Extension Type', type: 'string', required: true, default: 'CustomScriptExtension' },
      { name: 'type_handler_version', label: 'Type Handler Version', type: 'string', required: true, default: '1.8' },
      { name: 'auto_upgrade_minor_version', label: 'Auto Upgrade Minor Version', type: 'boolean', required: false, default: true },
      { name: 'settings', label: 'Settings (JSON)', type: 'object', required: false, default: { commandToExecute: '' } },
      { name: 'protected_settings', label: 'Protected Settings (JSON)', type: 'object', required: false },
    ],
    outputs: ['id', 'name'],
  },
  {
    type: 'azurerm_managed_disk',
    label: 'Managed Disk',
    category: 'storage',
    icon: 'HardDrive',
    provider: 'azure',
    description: 'Azure Managed Disk',
    inputs: [
      { name: 'name', label: 'Disk Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'storage_account_type', label: 'Storage Type', type: 'select', required: true, default: 'Standard_LRS', options: [
        { value: 'Standard_LRS', label: 'Standard LRS' },
        { value: 'Premium_LRS', label: 'Premium LRS' },
        { value: 'StandardSSD_LRS', label: 'Standard SSD LRS' },
        { value: 'UltraSSD_LRS', label: 'Ultra SSD LRS' },
      ]},
      { name: 'disk_size_gb', label: 'Disk Size (GB)', type: 'number', required: true, default: 30 },
    ],
    outputs: ['id', 'name', 'disk_size_gb'],
  },
  {
    type: 'azurerm_availability_set',
    label: 'Availability Set',
    category: 'compute',
    icon: 'Layers',
    provider: 'azure',
    description: 'Azure Availability Set for VMs',
    inputs: [
      { name: 'name', label: 'Availability Set Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'platform_fault_domain_count', label: 'Fault Domains', type: 'number', required: false, default: 2 },
      { name: 'platform_update_domain_count', label: 'Update Domains', type: 'number', required: false, default: 5 },
    ],
    outputs: ['id', 'name'],
  },
  {
    type: 'azurerm_storage_account',
    label: 'Storage Account',
    category: 'storage',
    icon: 'HardDrive',
    provider: 'azure',
    description: 'Azure Storage Account',
    inputs: [
      { name: 'name', label: 'Storage Account Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'account_tier', label: 'Account Tier', type: 'select', required: true, default: 'Standard', options: [
        { value: 'Standard', label: 'Standard' },
        { value: 'Premium', label: 'Premium' },
      ]},
      { name: 'account_replication_type', label: 'Replication', type: 'select', required: true, default: 'LRS', options: [
        { value: 'LRS', label: 'Locally Redundant' },
        { value: 'GRS', label: 'Geo-Redundant' },
        { value: 'ZRS', label: 'Zone Redundant' },
        { value: 'GZRS', label: 'Geo-Zone Redundant' },
      ]},
      { name: 'enable_https_traffic_only', label: 'HTTPS Only', type: 'boolean', required: false, default: true },
    ],
    outputs: ['id', 'name', 'primary_connection_string', 'primary_blob_endpoint'],
  },
  {
    type: 'azurerm_network_security_group',
    label: 'Network Security Group',
    category: 'security',
    icon: 'Shield',
    provider: 'azure',
    description: 'Azure Network Security Group',
    inputs: [
      { name: 'name', label: 'NSG Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'security_rules', label: 'Security Rules', type: 'array', required: false },
    ],
    outputs: ['id', 'name'],
  },
  {
    type: 'azurerm_public_ip',
    label: 'Public IP',
    category: 'network',
    icon: 'Globe',
    provider: 'azure',
    description: 'Azure Public IP Address',
    inputs: [
      { name: 'name', label: 'IP Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'allocation_method', label: 'Allocation', type: 'select', required: true, default: 'Dynamic', options: [
        { value: 'Dynamic', label: 'Dynamic' },
        { value: 'Static', label: 'Static' },
      ]},
      { name: 'sku', label: 'SKU', type: 'select', required: true, default: 'Basic', options: [
        { value: 'Basic', label: 'Basic' },
        { value: 'Standard', label: 'Standard' },
      ]},
    ],
    outputs: ['id', 'ip_address', 'fqdn'],
  },
  {
    type: 'azurerm_network_interface',
    label: 'Network Interface',
    category: 'network',
    icon: 'Network',
    provider: 'azure',
    description: 'Azure Network Interface Card',
    inputs: [
      { name: 'name', label: 'NIC Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'ip_configuration_name', label: 'IP Config Name', type: 'string', required: true, default: 'internal' },
      { name: 'subnet_id', label: 'Subnet ID', type: 'string', required: true },
      { name: 'private_ip_address_allocation', label: 'IP Allocation', type: 'select', required: false, default: 'Dynamic', options: [
        { value: 'Dynamic', label: 'Dynamic' },
        { value: 'Static', label: 'Static' },
      ]},
    ],
    outputs: ['id', 'name', 'mac_address', 'private_ip_address'],
  },
  {
    type: 'azurerm_lb',
    label: 'Load Balancer',
    category: 'network',
    icon: 'GitBranch',
    provider: 'azure',
    description: 'Azure Load Balancer',
    inputs: [
      { name: 'name', label: 'LB Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'sku', label: 'SKU', type: 'select', required: true, default: 'Standard', options: [
        { value: 'Basic', label: 'Basic' },
        { value: 'Standard', label: 'Standard' },
      ]},
    ],
    outputs: ['id', 'name', 'frontend_ip_configuration'],
  },
  {
    type: 'azurerm_key_vault',
    label: 'Key Vault',
    category: 'security',
    icon: 'Key',
    provider: 'azure',
    description: 'Azure Key Vault for secrets management',
    inputs: [
      { name: 'name', label: 'Key Vault Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'sku_name', label: 'SKU', type: 'select', required: true, default: 'standard', options: [
        { value: 'standard', label: 'Standard' },
        { value: 'premium', label: 'Premium' },
      ]},
      { name: 'enable_rbac_authorization', label: 'RBAC Authorization', type: 'boolean', required: false, default: false },
      { name: 'enable_soft_delete', label: 'Soft Delete', type: 'boolean', required: false, default: true },
      { name: 'purge_protection_enabled', label: 'Purge Protection', type: 'boolean', required: false, default: false },
    ],
    outputs: ['id', 'name', 'vault_uri'],
  },
  {
    type: 'azurerm_app_service',
    label: 'App Service',
    category: 'compute',
    icon: 'Globe',
    provider: 'azure',
    description: 'Azure App Service (Web App)',
    inputs: [
      { name: 'name', label: 'App Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'app_service_plan_id', label: 'App Service Plan', type: 'string', required: true },
      { name: 'https_only', label: 'HTTPS Only', type: 'boolean', required: false, default: true },
    ],
    outputs: ['id', 'name', 'default_site_hostname'],
  },
  {
    type: 'azurerm_app_service_plan',
    label: 'App Service Plan',
    category: 'compute',
    icon: 'Server',
    provider: 'azure',
    description: 'Azure App Service Plan',
    inputs: [
      { name: 'name', label: 'Plan Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'sku_name', label: 'SKU', type: 'select', required: true, default: 'F1', options: [
        { value: 'F1', label: 'Free F1' },
        { value: 'D1', label: 'Shared D1' },
        { value: 'B1', label: 'Basic B1' },
        { value: 'S1', label: 'Standard S1' },
        { value: 'P1v2', label: 'Premium P1v2' },
      ]},
    ],
    outputs: ['id', 'name'],
  },
  {
    type: 'azurerm_function_app',
    label: 'Function App',
    category: 'compute',
    icon: 'Zap',
    provider: 'azure',
    description: 'Azure Function App',
    inputs: [
      { name: 'name', label: 'Function App Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'app_service_plan_id', label: 'App Service Plan', type: 'string', required: true },
      { name: 'storage_account_name', label: 'Storage Account', type: 'string', required: true },
      { name: 'https_enabled', label: 'HTTPS Enabled', type: 'boolean', required: false, default: true },
    ],
    outputs: ['id', 'name', 'default_hostname'],
  },
  {
    type: 'azurerm_sql_database',
    label: 'SQL Database',
    category: 'database',
    icon: 'Database',
    provider: 'azure',
    description: 'Azure SQL Database',
    inputs: [
      { name: 'name', label: 'Database Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'server_name', label: 'SQL Server', type: 'string', required: true },
      { name: 'sku_name', label: 'SKU Name', type: 'select', required: true, default: 'S0', options: [
        { value: 'S0', label: 'Standard S0' },
        { value: 'S1', label: 'Standard S1' },
        { value: 'P1v2', label: 'Premium P1v2' },
      ]},
    ],
    outputs: ['id', 'name', 'fqdn'],
  },
  {
    type: 'azurerm_cosmosdb_account',
    label: 'Cosmos DB',
    category: 'database',
    icon: 'Database',
    provider: 'azure',
    description: 'Azure Cosmos DB (NoSQL Database)',
    inputs: [
      { name: 'name', label: 'Account Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'kind', label: 'API Kind', type: 'select', required: true, default: 'GlobalDocumentDB', options: [
        { value: 'GlobalDocumentDB', label: 'SQL API' },
        { value: 'MongoDB', label: 'MongoDB API' },
        { value: 'Cassandra', label: 'Cassandra' },
        { value: 'Table', label: 'Table API' },
      ]},
    ],
    outputs: ['id', 'name', 'endpoint'],
  },
  {
    type: 'azurerm_kubernetes_cluster',
    label: 'AKS Cluster',
    category: 'kubernetes',
    icon: 'GitBranch',
    provider: 'azure',
    description: 'Azure Kubernetes Service Cluster',
    inputs: [
      { name: 'name', label: 'Cluster Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'dns_prefix', label: 'DNS Prefix', type: 'string', required: true },
      { name: 'sku_tier', label: 'SKU Tier', type: 'select', required: false, default: 'Free', options: [
        { value: 'Free', label: 'Free' },
        { value: 'Paid', label: 'Paid' },
      ]},
      { name: 'default_node_pool', label: 'Node Pool Name', type: 'string', required: true, default: 'default' },
      { name: 'node_count', label: 'Node Count', type: 'number', required: false, default: 3 },
      { name: 'vm_size', label: 'Node VM Size', type: 'select', required: true, default: 'Standard_DS2_v2', options: azureVMSizes.generalPurpose.slice(0, 30) },
    ],
    outputs: ['id', 'name', 'kube_config', 'fqdn'],
  },
  {
    type: 'azurerm_container_registry',
    label: 'Container Registry',
    category: 'storage',
    icon: 'Package',
    provider: 'azure',
    description: 'Azure Container Registry',
    inputs: [
      { name: 'name', label: 'Registry Name', type: 'string', required: true },
      { name: 'location', label: 'Location', type: 'string', required: true, default: 'eastus' },
      { name: 'resource_group', label: 'Resource Group', type: 'string', required: true },
      { name: 'sku', label: 'SKU', type: 'select', required: true, default: 'Basic', options: [
        { value: 'Basic', label: 'Basic' },
        { value: 'Standard', label: 'Standard' },
        { value: 'Premium', label: 'Premium' },
      ]},
    ],
    outputs: ['id', 'name', 'login_server'],
  },
]

export const awsResources: ResourceDefinition[] = [
  {
    type: 'aws_ec2_instance',
    label: 'EC2 Instance',
    category: 'compute',
    icon: 'Server',
    provider: 'aws',
    description: 'Virtual server in AWS',
    inputs: [
      { name: 'ami', label: 'AMI ID', type: 'string', required: true, default: 'ami-0c55b159cbfafe1f0' },
      { name: 'instance_type', label: 'Instance Type', type: 'select', required: true, default: 't3.micro', options: [
        { value: 't3.micro', label: 't3.micro' },
        { value: 't3.small', label: 't3.small' },
        { value: 't3.medium', label: 't3.medium' },
        { value: 't3.large', label: 't3.large' },
      ]},
      { name: 'subnet_id', label: 'Subnet ID', type: 'string', required: false },
    ],
    outputs: ['id', 'public_ip', 'private_ip'],
  },
  {
    type: 'aws_s3_bucket',
    label: 'S3 Bucket',
    category: 'storage',
    icon: 'HardDrive',
    provider: 'aws',
    description: 'Object storage bucket',
    inputs: [
      { name: 'bucket', label: 'Bucket Name', type: 'string', required: true },
      { name: 'acl', label: 'ACL', type: 'select', required: false, default: 'private', options: [
        { value: 'private', label: 'Private' },
        { value: 'public-read', label: 'Public Read' },
      ]},
    ],
    outputs: ['arn', 'bucket_domain_name'],
  },
  {
    type: 'aws_vpc',
    label: 'VPC',
    category: 'network',
    icon: 'Network',
    provider: 'aws',
    description: 'Virtual Private Cloud',
    inputs: [
      { name: 'cidr_block', label: 'CIDR Block', type: 'string', required: true, default: '10.0.0.0/16' },
    ],
    outputs: ['id', 'cidr_block'],
  },
  {
    type: 'aws_subnet',
    label: 'Subnet',
    category: 'network',
    icon: 'Network',
    provider: 'aws',
    description: 'VPC subnet',
    inputs: [
      { name: 'vpc_id', label: 'VPC ID', type: 'string', required: true },
      { name: 'cidr_block', label: 'CIDR Block', type: 'string', required: true },
    ],
    outputs: ['id', 'cidr_block'],
  },
  {
    type: 'aws_security_group',
    label: 'Security Group',
    category: 'security',
    icon: 'Shield',
    provider: 'aws',
    description: 'Firewall rules for resources',
    inputs: [
      { name: 'name', label: 'Name', type: 'string', required: true },
      { name: 'vpc_id', label: 'VPC ID', type: 'string', required: true },
    ],
    outputs: ['id', 'arn'],
  },
  {
    type: 'aws_rds_instance',
    label: 'RDS Instance',
    category: 'database',
    icon: 'Database',
    provider: 'aws',
    description: 'Managed database instance',
    inputs: [
      { name: 'identifier', label: 'Instance Identifier', type: 'string', required: true },
      { name: 'engine', label: 'Engine', type: 'select', required: true, default: 'mysql', options: [
        { value: 'mysql', label: 'MySQL' },
        { value: 'postgres', label: 'PostgreSQL' },
      ]},
      { name: 'instance_class', label: 'Instance Class', type: 'select', required: true, default: 'db.t3.micro', options: [
        { value: 'db.t3.micro', label: 'db.t3.micro' },
        { value: 'db.t3.small', label: 'db.t3.small' },
      ]},
      { name: 'allocated_storage', label: 'Allocated Storage (GB)', type: 'number', required: true, default: 20 },
    ],
    outputs: ['id', 'endpoint', 'port'],
  },
  {
    type: 'aws_lambda_function',
    label: 'Lambda Function',
    category: 'compute',
    icon: 'Zap',
    provider: 'aws',
    description: 'Serverless function',
    inputs: [
      { name: 'function_name', label: 'Function Name', type: 'string', required: true },
      { name: 'runtime', label: 'Runtime', type: 'select', required: true, default: 'nodejs18.x', options: [
        { value: 'nodejs18.x', label: 'Node.js 18' },
        { value: 'python3.11', label: 'Python 3.11' },
      ]},
      { name: 'handler', label: 'Handler', type: 'string', required: true, default: 'index.handler' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', required: false, default: 30 },
    ],
    outputs: ['id', 'arn'],
  },
]

export const k8sResources: ResourceDefinition[] = [
  {
    type: 'kubernetes_deployment',
    label: 'Deployment',
    category: 'kubernetes',
    icon: 'Package',
    provider: 'kubernetes',
    description: 'Kubernetes Deployment',
    inputs: [
      { name: 'name', label: 'Name', type: 'string', required: true },
      { name: 'namespace', label: 'Namespace', type: 'string', required: false, default: 'default' },
      { name: 'replicas', label: 'Replicas', type: 'number', required: false, default: 3 },
      { name: 'image', label: 'Container Image', type: 'string', required: true },
      { name: 'port', label: 'Container Port', type: 'number', required: false, default: 80 },
    ],
    outputs: ['name', 'replicas'],
  },
  {
    type: 'kubernetes_service',
    label: 'Service',
    category: 'kubernetes',
    icon: 'Network',
    provider: 'kubernetes',
    description: 'Kubernetes Service',
    inputs: [
      { name: 'name', label: 'Name', type: 'string', required: true },
      { name: 'namespace', label: 'Namespace', type: 'string', required: false, default: 'default' },
      { name: 'type', label: 'Service Type', type: 'select', required: true, default: 'ClusterIP', options: [
        { value: 'ClusterIP', label: 'ClusterIP' },
        { value: 'NodePort', label: 'NodePort' },
        { value: 'LoadBalancer', label: 'LoadBalancer' },
      ]},
      { name: 'ports', label: 'Ports', type: 'array', required: true },
    ],
    outputs: ['cluster_ip', 'external_ip'],
  },
  {
    type: 'kubernetes_configmap',
    label: 'ConfigMap',
    category: 'kubernetes',
    icon: 'FileJson',
    provider: 'kubernetes',
    description: 'Kubernetes ConfigMap',
    inputs: [
      { name: 'name', label: 'Name', type: 'string', required: true },
      { name: 'namespace', label: 'Namespace', type: 'string', required: false, default: 'default' },
      { name: 'data', label: 'Data', type: 'object', required: false },
    ],
    outputs: ['name'],
  },
  {
    type: 'kubernetes_secret',
    label: 'Secret',
    category: 'kubernetes',
    icon: 'Lock',
    provider: 'kubernetes',
    description: 'Kubernetes Secret',
    inputs: [
      { name: 'name', label: 'Name', type: 'string', required: true },
      { name: 'namespace', label: 'Namespace', type: 'string', required: false, default: 'default' },
      { name: 'type', label: 'Secret Type', type: 'select', required: true, default: 'Opaque', options: [
        { value: 'Opaque', label: 'Opaque' },
        { value: 'kubernetes.io/tls', label: 'TLS Certificate' },
      ]},
    ],
    outputs: ['name'],
  },
  {
    type: 'kubernetes_ingress',
    label: 'Ingress',
    category: 'kubernetes',
    icon: 'Globe',
    provider: 'kubernetes',
    description: 'Kubernetes Ingress',
    inputs: [
      { name: 'name', label: 'Name', type: 'string', required: true },
      { name: 'namespace', label: 'Namespace', type: 'string', required: false, default: 'default' },
      { name: 'ingress_class', label: 'Ingress Class', type: 'string', required: true, default: 'nginx' },
    ],
    outputs: ['name', 'host'],
  },
]

export const allResources = [...awsResources, ...azureResources, ...k8sResources]

export const getResourceByType = (type: string): ResourceDefinition | undefined => {
  return allResources.find((r) => r.type === type)
}

export const getResourcesByCategory = (category: string): ResourceDefinition[] => {
  return allResources.filter((r) => r.category === category)
}

export const getResourcesByProvider = (provider: string): ResourceDefinition[] => {
  return allResources.filter((r) => r.provider === provider)
}